name: Java Playground security vulnerability
description: Pontential vulnerabilities should be reported to https://www.oracle.com/corporate/security-practices/assurance/vulnerability/reporting.html
title: "[vulnerability]:"
body:
  - type: markdown
    attributes:
      value: |     
        If you believe you have found a security vulnerability in the Java Playground please report it through [Oracle's Security Vulnerability reporting process](https://www.oracle.com/corporate/security-practices/assurance/vulnerability/reporting.html).
        Thanks for taking the time to fill out this bug report!
 - type: checkboxes
    id: OK
    attributes:
      label: OK
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: OK
          required:false
          
