name: Java DevRel Websites
description: Issue(s) and suggestion(s) related to Java DevRel websites, ex. https://inside.java, https://dev.java, etc.
title: "[Web]:"
labels: ["Web"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this report.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: "Also tell us, what did you expect to happen? Make sure to inlcude any relevant information inlcuding the URL. If needed, you can upload screeshot(s) in this area."
      placeholder: Please, tell us what you see and on which site.
      value: "An issue happened!"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What OS are you seeing the problem on?
      multiple: false
      options:
        - Linux 
        - macOS
        - Windows
        - iOS
        - Android
        - Other
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Brave
        - Microsoft Edge
        - Other
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details (optional)
      description: If you agree to be contacted should we need more info, please leave your email. Note that your email will be visible in this report.
      placeholder: ex. email@example.com
    validations:
      required: false

